In [29]:
# Import libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
# https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html

from sklearn.metrics.pairwise import cosine_similarity

In [3]:
# Load dataset
df = pd.read_csv("../Data/clean_parsed_tmdb_5000.csv")

In [8]:
df.head()

budget                                       genres  \
0  237000000  Action, Adventure, Fantasy, Science Fiction   
1  300000000                   Adventure, Fantasy, Action   
2  245000000                     Action, Adventure, Crime   
3  250000000               Action, Crime, Drama, Thriller   
4  260000000           Action, Adventure, Science Fiction   

                                       homepage  \
0                   http://www.avatarmovie.com/   
1  http://disney.go.com/disneypictures/pirates/   
2   http://www.sonypictures.com/movies/spectre/   
3            http://www.thedarkknightrises.com/   
4          http://movies.disney.com/john-carter   

                                            keywords original_language  \
0  culture clash, future, space war, space colony...                en   
1  ocean, drug abuse, exotic island, east india t...                en   
2  spy, based on novel, secret agent, sequel, mi6...                en   
3  dc comics, crime fighter, terrorist, secret id...                en   
4  based on novel, mars, medallion, space travel,...                en   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  Ingenious Film Partners, Twentieth Century Fox...   
1  Walt Disney Pictures, Jerry Bruckheimer Films,...   
2                     Columbia Pictures, Danjaq, B24   
3  Legendary Pictures, Warner Bros., DC Entertain...   
4                               Walt Disney Pictures   

                       production_countries release_date     revenue  runtime  \
0  United States of America, United Kingdom   2009-12-10  2787965087    162.0   
1                  United States of America   2007-05-19   961000000    169.0   
2  United Kingdom, United States of America   2015-10-26   880674609    148.0   
3                  United States of America   2012-07-16  1084939099    165.0   
4                  United States of America   2012-03-07   284139100    132.0   

                                spoken_languages    status  \
0                               English, Español  Released   
1                                        English  Released   
2  Français, English, Español, Italiano, Deutsch  Released   
3                                        English  Released   
4                                        English  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  \
0                                    Avatar           7.2       11800   
1  Pirates of the Caribbean: At World's End           6.9        4500   
2                                   Spectre           6.3        4466   
3                     The Dark Knight Rises           7.6        9106   
4                               John Carter           6.1        2124   

                                                cast  \
0  Sam Worthington, Zoe Saldana, Sigourney Weaver...   
1  Johnny Depp, Orlando Bloom, Keira Knightley, S...   
2  Daniel Craig, Christoph Waltz, Léa Seydoux, Ra...   
3  Christian Bale, Michael Caine, Gary Oldman, An...   
4  Taylor Kitsch, Lynn Collins, Samantha Morton, ...   

                                                crew  
0  Stephen E. Rivkin (Editor), Rick Carter (Produ...  
1  Dariusz Wolski (Director of Photography), Gore...  
2  Thomas Newman (Ori

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4802 entries, 0 to 4801
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   budget                4802 non-null   int64  
 1   genres                4775 non-null   object 
 2   homepage              1712 non-null   object 
 3   keywords              4391 non-null   object 
 4   original_language     4802 non-null   object 
 5   overview              4799 non-null   object 
 6   popularity            4802 non-null   float64
 7   production_companies  4452 non-null   object 
 8   production_countries  4629 non-null   object 
 9   release_date          4802 non-null   object 
 10  revenue               4802 non-null   int64  
 11  runtime               4802 non-null   float64
 12  spoken_languages      4716 non-null   object 
 13  status                4802 non-null   object 
 14  tagline               3959 non-null   object 
 15  title                

In [13]:
# Combine all content into a single text field
df["combined_content"] = (
    df["genres"].astype(str) + " " +
    df["keywords"].astype(str) + " " +
    df["overview"].astype(str) + " " +
    df["production_companies"].astype(str) + " " +
    df["tagline"].astype(str) + " " +
    df["cast"].astype(str) + " " +
    df["crew"].astype(str)
)

In [21]:
# Convert everything to lowercase
df["combined_content"] = df["combined_content"].astype(str).str.lower()

# Replace anything that's not a letter or number with whitespace
df["combined_content"] = df["combined_content"].str.replace(r'[^\w\s]', '', regex=True)

# Strip trailing whitespace
df["combined_content"] = df["combined_content"].str.strip()

In [23]:
df["combined_content"]

0       action adventure fantasy science fiction cultu...
1       adventure fantasy action ocean drug abuse exot...
2       action adventure crime spy based on novel secr...
3       action crime drama thriller dc comics crime fi...
4       action adventure science fiction based on nove...
                              ...                        
4797    action crime thriller united statesmexico barr...
4798    comedy romance nan a newlywed couples honeymoo...
4799    comedy drama romance tv movie date love at fir...
4800    nan nan when ambitious new york attorney sam i...
4801    documentary obsession camcorder crush dream gi...
Name: combined_content, Length: 4802, dtype: object

In [25]:
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)

In [27]:
# Create a matrix by fitting the TF-IDF model
tfidf_matrix = vectorizer.fit_transform(df["combined_content"])

In [31]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 443871 stored elements and shape (4802, 5000)>

In [30]:
similarity_matrix = cosine_similarity(tfidf_matrix)

In [32]:
similarity_matrix

array([[1.        , 0.19578554, 0.66291794, ..., 0.04589267, 0.01466897,
        0.02389071],
       [0.19578554, 1.        , 0.15682752, ..., 0.07075526, 0.01271746,
        0.02324541],
       [0.66291794, 0.15682752, 1.        , ..., 0.05500419, 0.04229058,
        0.01561895],
       ...,
       [0.04589267, 0.07075526, 0.05500419, ..., 1.        , 0.03705502,
        0.04878338],
       [0.01466897, 0.01271746, 0.04229058, ..., 0.03705502, 1.        ,
        0.02449469],
       [0.02389071, 0.02324541, 0.01561895, ..., 0.04878338, 0.02449469,
        1.        ]], shape=(4802, 4802))

In [33]:
similarity_matrix.shape

(4802, 4802)

In [71]:
movie_index = df[df['title'] == 'Frozen'].index[0]

In [72]:
# Compute similarity to chosen movie
scores = similarity_matrix[movie_index]


In [73]:
scores

array([0.12497305, 0.09978126, 0.14784295, ..., 0.0407065 , 0.01742178,
       0.01736454], shape=(4802,))

In [74]:
similar_indices

array([ 343,  231,   66,  722,  130,  742,  339,  533, 1257, 3271])

In [75]:
# Find the indices 10 most similar movies
similar_indices = scores.argsort()[::-1][1:11]

In [76]:
# Display the most similar movies
df['title'].iloc[similar_indices]

874                            Anastasia
1620                     Winnie the Pooh
812                           Pocahontas
66                                    Up
6                                Tangled
558                   The Simpsons Movie
2821     Beavis and Butt-Head Do America
459     Spirit: Stallion of the Cimarron
130                                 Bolt
88                            Big Hero 6
Name: title, dtype: object